### ISSUE TITLE
Nextra 3

### ISSUE THREAD

**Issue by dimaMachina** [shuding/nextra#1421]
below of my thoughts on the next biggest release

- [x] allow only ESM config `next.config.mjs` or `next.config.js` with `"type": "module"` https://github.com/shuding/nextra/pull/2254

> the whole nextra should be bundled to ESM only instead of mixing cjs and esm

> also this should fix blocked renovate PRs https://github.com/shuding/nextra/pull/1136 https://github.com/shuding/nextra/pull/1083 which one now ESM only

- [x] implement new i18n proposal https://github.com/shuding/nextra/issues/176 https://github.com/shuding/nextra/pull/2070

- [x] add support for `_meta.{js,jsx,ts,tsx}` with JSX support https://github.com/shuding/nextra/issues/852 https://github.com/shuding/nextra/pull/2272

> this should fix the following https://github.com/shuding/nextra/issues/1263 and avoid future bugs with redirects of https://github.com/shuding/nextra/issues/1354 https://github.com/shuding/nextra/issues/1402

- [ ] official versioning support + new docs on how to setup it https://github.com/shuding/nextra/issues/20

- [ ] set by default `loaderOptions.defaultShowCopyCode` to `true` and in `compileMdx` also
- `nextra-theme-docs`
  - [x] set by default `sidebar.toggleButton` to `true` https://github.com/shuding/nextra/pull/2248
  - [x] made a renames of theme configs for `nextra-theme-docs` https://github.com/shuding/nextra/issues/826 https://github.com/shuding/nextra/pull/2258
  - [x] remove `newNextLinkBehavior` option and in nextra loader also https://github.com/shuding/nextra/pull/2070
  - [x] <s>remove custom `<Anchor />` component and use plain `NextLink` everywhere</s>
  - [x] <s>https://github.com/shuding/nextra/issues/332</s>
  - [x] remove Steps, Callout, Tabs, Cards, FileTree exports https://github.com/shuding/nextra/pull/2248
- `nextra-theme-blog`
  - [x] use  `NextLink` without `legacyBehavior` prop https://github.com/shuding/nextra/pull/2252
  - [ ] validate theme config options with zod?
  - [x] remove config.cusdis. Pass cusdis options as props in Cusdis component https://github.com/shuding/nextra/pull/2252
 
- [x] set `next` 13 as minimal supported version https://github.com/shuding/nextra/pull/2249
- [x] rename `nextra/ssg` to `nextra/data` https://github.com/shuding/nextra/pull/2251
- [x] remove the current workaround to allow import MDX outside of CWD and add `console.error` if there are such as cases https://github.com/shuding/nextra/issues/1424#issuecomment-1408748932 https://github.com/shuding/nextra/pull/2251
- [x] prefer to use _app.tsx/jsx over _app.mdx https://github.com/shuding/nextra/issues/1632#issuecomment-1466598199 https://github.com/shuding/nextra/pull/2070
- [x] Remove `Tab` in favour `Tabs.Tab`, remove `Card` in favour `Cards.Card` https://github.com/shuding/nextra/pull/2251

- [ ] update `remark-math` to v6 https://github.com/shuding/nextra/issues/2368
tbd

**Comment by juliusmarminge** [comment]
You got a rough timeline for this release?

**Comment by B2o5T** [comment]
@juliusmarminge nope

**Comment by pomber** [comment]
any plans for experimental support for React Server Components? or you'll wait for a stable `app` directory?

**Comment by ecraig12345** [comment]
Whatever features you include, please try to document the breaking changes better. Migrating a simple site from 1 to 2 was a big headache due to the lack of documentation about renamed settings and other changes.

**Comment by B2o5T** [comment]
> Whatever features you include, please try to document the breaking changes better. Migrating a simple site from 1 to 2 was a big headache due to the lack of documentation about renamed settings and other changes.

Which renamed settings were not documented and _other changes_?

**Comment by ecraig12345** [comment]
> > Whatever features you include, please try to document the breaking changes better. Migrating a simple site from 1 to 2 was a big headache due to the lack of documentation about renamed settings and other changes.
> 
> Which renamed settings were not documented and _other changes_?

[This discussion](https://github.com/shuding/nextra/discussions/257) was the only migration/upgrade guide I could find. It doesn't mention any of the renamed settings (specifically for `nextra-theme-docs` config in my case), and it's not linked from the changelog or anywhere else that I saw (I found it with search). 

Looking again at the [nextra-theme-docs changelog](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/CHANGELOG.md#patch-changes-23), I now see there is an entry for "various theme config options was renamed" (under "patch" which is incorrect for a breaking change), but just linking out to a code file which doesn't mention the old names is not very helpful. There were also some settings like the `search` and `footer` where the expected type changed from boolean to object.

The other break I noticed was an `nx-` prefix was added to class names (some of the code in the site I was upgrading used those), though I'm not sure if those were intended for public use.

The simplest way to make future upgrades easier for your users is to make sure that any breaking changes have a changeset with type "major" (with a detailed description of any breaks) so that they end up in the "Major changes" section of the changelog--that would probably have been enough to help me. But it also doesn't hurt to have a separate upgrade/migration guide, sort of like these ones for [Next.js](https://nextjs.org/docs/upgrading), [ESLint](https://eslint.org/docs/latest/use/migrate-to-8.0.0), or [Fluent UI React](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#individual-components-breaking-changes) (those are much larger tools/libraries, but it shows the general idea).

It might also be worth more explicitly calling out that there were styling changes, with before/after screenshots of a demo site so people can see how their site will change (though this isn't quite as important, since it's automatic and people can see it in local testing). The parts of the v2 styling changes that confused me were the footer moving from the bottom of the main column to the bottom of the page, and the edit link moving from the footer to the right sidebar. When testing, I thought the edit link had disappeared or maybe I was missing a setting to make it show up--but it turns out this was just because my window width was under 1280px (laptop screen with vertical tabs) and the right sidebar isn't shown at that width. A before/after screenshot would have clarified that the link had moved and my screen was too small to see it.

**Comment by B2o5T** [comment]
> https://github.com/shuding/nextra/discussions/257 was the only migration/upgrade guide I could find. It doesn't mention any of the renamed settings (specifically for nextra-theme-docs config in my case), and it's not linked from the changelog or anywhere else that I saw (I found it with search).

For theme config options just look at docs page https://nextra.site/docs/docs-theme/theme-configuration
Also, I made setup zod validation of theme config options to avoid typos, also you can use `theme.config.tsx` file and import `DocsThemeConfig` type

> Looking again at the [nextra-theme-docs changelog](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/CHANGELOG.md?rgh-link-date=2023-04-21T18%3A31%3A50Z#patch-changes-23), I now see there is an entry for "various theme config options was renamed" (under "patch" which is incorrect for a breaking change), but just linking out to a code file which doesn't mention the old names is not very helpful. There were also some settings like the search and footer where the expected type changed from boolean to object.

Not a big deal, the most important thing is that it was released as Major release

> The other break I noticed was an nx- prefix was added to class names (some of the code in the site I was upgrading used those), though I'm not sure if those were intended for public use.

it was made to avoid conflicts with the user's tailwind config

> The simplest way to make future upgrades easier for your users is to make sure that any breaking changes have a changeset with type "major" (with a detailed description of any breaks) so that they end up in the "Major changes" section of the changelog--that would probably have been enough to help me.

we already use changesets, we had 100 alpha releases and we can't catch everything

> But it also doesn't hurt to have a separate upgrade/migration guide, sort of like these ones for [Next.js](https://nextjs.org/docs/upgrading), [ESLint](https://eslint.org/docs/latest/use/migrate-to-8.0.0), or [Fluent UI React](https://github.com/microsoft/fluentui/wiki/Version-8-migration-guide#individual-components-breaking-changes) (those are much larger tools/libraries, but it shows the general idea).

Unfortunately, Nextra is not a such popular as your mentioned repository where there are 5-10 maintainers and a LOT of contributors, we try to improve it as we can

> It might also be worth more explicitly calling out that there were styling changes, with before/after screenshots of a demo site so people can see how their site will change (though this isn't quite as important, since it's automatic and people can see it in local testing). The parts of the v2 styling changes that confused me were the footer moving from the bottom of the main column to the bottom of the page, and the edit link moving from the footer to the right sidebar. When testing, I thought the edit link had disappeared or maybe I was missing a setting to make it show up--but it turns out this was just because my window width was under 1280px (laptop screen with vertical tabs) and the right sidebar isn't shown at that width. A before/after screenshot would have clarified that the link had moved and my screen was too small to see it.

As I mentioned I can't cover everything just feel free to contribute, @shuding already write amazing docs for Nextra v2

**Comment by jacfra** [comment]
Would you consider add `nodejs` style `index` files?

i.e. instead of defining the `index` file as the same name as the directory one level above the folder allow the `index` file to be named `index` so it can easily be copy-pasted with the existing sub-folder and `_meta.json`

This should be possible because the `_meta.json` already handles renaming files. 

i.e. if you wanted the file to be named `index` on the sidebar or nav bar you can name the file `{{name}}.mdx` and update the naming convention in `_meta.json` to name the title of the file `index`

**Comment by dacevedo12** [comment]
Any chance of supporting turbopack in the next major or will nextra wait for a stable release?

https://github.com/shuding/nextra/issues/1054

**Comment by B2o5T** [comment]
@dacevedo12 no chances, pr welcome

**Comment by abenhamdine** [comment]
> Thank you very much for this project and I can't wait to use the Nextra 3. `https://grpcity.vercel.app/ ` is the use of the Nextra 3 online example, running very well, thanks again.

is that site built with v3 branch ?
Did you encounter any bug/gotcha ?

**Comment by chakhsu** [comment]
> > Thank you very much for this project and I can't wait to use the Nextra 3. `https://grpcity.vercel.app/ ` is the use of the Nextra 3 online example, running very well, thanks again.
> 
> I see that this site has been built with v3 branch https://github.com/chakhsu/grpcity-docs/blob/56e95759c2510d9103892e81dd6e28aeeba54eba/package.json#L21 Did you encounter any bug/gotcha ?

I didn't encounter a bug. I just make sure that the configuration and usage are the same as in the v3 example.

**Comment by GraceWalk** [comment]
I encountered a bug. When I open https://grpcity.js.org/en and manually enter gPRCity is a simple in the search bar, an error will be reported.

**Comment by abenhamdine** [comment]
> I encountered a bug. When I open [grpcity.js.org/en](https://grpcity.js.org/en) and manually enter "gPRCity is a simple" in the search bar, an error will be reported.

Which error ? I tried to reproduce it without success

**Comment by GraceWalk** [comment]
> Which error ? I tried to reproduce it without success

Application error: a client-side exception has occurred (see the browser console for more information).

I used "Arc 1.17.2 (43249) Chromium Engine Version 119.0.6045.159"


![20231129-103051](https://github.com/shuding/nextra/assets/45837617/22bb3ab5-fa23-4cc5-b5d9-1703e9052a4c)

**Comment by abenhamdine** [comment]
I have no error in console,
I tried with Chrome Version 119.0.6045.160 (Build officiel) (64 bits)
You should try with incognito mode, to see if an extension would be the culprit

**Comment by GraceWalk** [comment]
> I have no error in console, I tried with Chrome Version 119.0.6045.160 (Build officiel) (64 bits), Windows OS You should try with incognito mode, to see if an extension would be the culprit

You are correct, it is indeed a browser extension causing the problem. I tried turning off the extension and the search function worked fine. ignore this question

**Comment by dimaMachina** [comment]
For anyone wants to try Nextra 3 here is my blog post with all the features and a migration guide from Nextra 2

https://the-guild.dev/blog/nextra-3

**Comment by SaadBazaz** [comment]
Been waiting for Nextra 3 for too long <3

However, would really really need appDir support. Bumping up to >= Next 13 does not make sense if we can't use the new router; we're pretty much stuck at Next 13 because 14 doesn't even have the pages dir.

Need this in appDir because I want to build a hybrid site which can have both docs and SaaS. Less maintenance, single repo, shared providers... that's the sweet deal.

**Comment by SaadBazaz** [comment]
I'm more of a monolith guy :p
I was thinking of having tight knit integration between my docs, and SaaS. That's why was preferring to have just App Router.
```
app
|_ (docs)
|_ (saas-tool)
|_ layout.tsx
```

I thought Next was deprecating pages as they moved forward? It's still in the air and I wouldn't risk being on an old architecture for such an awesome library like Nextra which, honestly, has great potential to be the go-to static site maker.

**Comment by SaadBazaz** [comment]
I think from here onwards, given all the effort put in by the awesome @dimaMachina , a good way forward is: 1) make a shittonne of good templates for Nextra 3, 2) Separate the Nextra Components library and give devs easy access to add more components (Maybe using shadcn/ui or Radix as a base design system would help in that), 3) Putting major effort in appDir migration.

**Comment by dimaMachina** [comment]
⚠️ Nextra 3 will not have support for the app router, please move all discussions and ideas related to the app router in according pinned issue https://github.com/shuding/nextra/issues/2023

**Comment by hariria** [comment]
@dimaMachina any ETA on when we will be able to try this out? Would rather use Nextra 3 than 2 if it's coming out soon

**Comment by dimaMachina** [comment]
@hariria you can already try v3 alpha version, there is no date when it will be released since I maintain this framework alone

**Comment by maciejkwas** [comment]
@SaadBazaz were you successful on getting your setup right? I need exactly same structure but with i18n support, would you like to collab to get some PR maybe on that?

**Comment by dimaMachina** [comment]
@maciejkwas https://github.com/shuding/nextra/tree/v3/examples/swr-site here is working i18n example

**Comment by Genesis3800** [comment]
Hey @dimaMachina lots of love and regards to you for what you've built.
Really excited for Nextra 3.
Do you have a rough timeline right now for when it might be ready for stable release?

**Comment by dimaMachina** [comment]
> Hey @dimaMachina lots of love and regards to you for what you've built. Really excited for Nextra 3. Do you have a rough timeline right now for when it might be ready for stable release?

Thank you 🙌.
The stable release will be released once I will polish own Nextra 3 docs to include new changes, I can't say when it will be done.
Also, I already started work on Nextra 4 with app router support, so more amazing things coming this year.

**Comment by Genesis3800** [comment]
> > Hey @dimaMachina lots of love and regards to you for what you've built. Really excited for Nextra 3. Do you have a rough timeline right now for when it might be ready for stable release?
> 
> Thank you 🙌. The stable release will be released once I will polish own Nextra 3 docs to include new changes, I can't say when it will be done. Also, I already started work on Nextra 4 with app router support, so more amazing things coming this year.

Haha fair enough. We at my work are looking forward to versioning support, plus the upgrade to `_meta.tsx` . If there's any way I can help (I am a technical writer) please let me know.
It'll be an honor if I can help with the release in any way.

**Comment by dimaMachina** [comment]
@Genesis3800 thank you! It would be a huge help with v3 release 🙏.

If you want to help with docs updates
- please go to https://github.com/shuding/nextra/pull/2245, and use this PR as base branch
- once you are `v3` branch run `pnpm dev:website` to run `nextra.site` locally
- go over all existing docs and update them according to [the-guild.dev/blog/nextra-3](https://the-guild.dev/blog/nextra-3) changes
- try to create separated PRs to make review easy

**Comment by equinusocio** [comment]
> https://the-guild.dev/blog/nextra-3#replacement-shiki-by-shikiji
- Shikiji is deprecated and merged into original shiki

- Next is now at 14.2

**Comment by mmkal** [comment]
Hi, not sure this is the right place to put this, but I didn't want to create a new issue since v3 is in alpha.

Looks like there's a small CSS bug in `` ``` `` blocks (at least, single line ones that don't have a language tag - see the left padding):

Example: https://www.pgkit.dev/packages/migrator - source code here: https://github.com/mmkal/slonik-tools/blob/pgkit/apps/docs/pages/packages/migrator.md

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/a8116c46-d017-46b4-9207-e49f0816d10d">

It doesn't seem to affect code blocks:

<img width="890" alt="image" src="https://github.com/user-attachments/assets/c366a203-4078-4597-b193-ea6200e40683">

Also, the `backgroundColor.dark` property didn't seem to do anything - note that the above page is in the normal colour even though I set `backgroundColor.dark = 'green'`: https://github.com/mmkal/slonik-tools/blob/pgkit/apps/docs/theme.config.tsx#L24-L27

**Comment by dimaMachina** [comment]
> Looks like there's a small CSS bug in ``` blocks (at least, single line ones that don't have a language tag - see the left padding):

bug, will be fixed

> Also, the backgroundColor.dark property didn't seem to do anything - note that the above page is in the normal colour even though I set backgroundColor.dark = 'green'

use `0,255,0` for `green`

**Comment by equinusocio** [comment]
Any hope to see this fixed with v3?

https://github.com/shuding/nextra/issues/1403


The most easy and basic fix is this:

**Comment by logemann** [comment]
Looks like we cant use Nextra with React19 because of this:
https://github.com/shuding/nextra/pull/3037#issuecomment-2304496499

Are there any efforts to upgrade to latest headlessui/react so that we can use Nextra with a React19 NextJS project?

**Comment by equinusocio** [comment]
This project is semi-dead. I'm currently switching to Vocs

**Comment by logemann** [comment]
Configuring sidebar menus with explicit definition instead using the folder structure? No thanks. ;-)

**Comment by Genesis3800** [comment]
@logemann I don't understand:

1. Even now, you need to create individual `_meta.json` files to define sidebar menus with any sort of complexity at all. For example, [something like this](https://docs.availproject.org/api-reference/avail-node-api/da-create-application-key) requires a bit of refining in the `_meta.json`
2. Configuring sidebar menus with explicit definitions isn't unprecedented either, Docusaurus does it that way only.

**Comment by dimaMachina** [comment]
Nextra 3 is finally released today, feel free to update and create new issues, I will lock this thread to avoid spamming those who had a notification enabled on this PR

Blog post / migration guide https://the-guild.dev/blog/nextra-3

Nextra 4 with app router support and server components will coming next, feel free to try v4 alpha versions as well https://github.com/shuding/nextra/releases/tag/nextra%404.0.0-app-router.3
https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%404.0.0-app-router.3
https://github.com/shuding/nextra/releases/tag/nextra-theme-blog%404.0.0-app-router.3
