### ISSUE TITLE
Nextra 4

### ISSUE THREAD

**Issue by dimaMachina** [shuding/nextra#2600]
- [x] drop support `pages` router, support `app` router instead https://github.com/shuding/nextra/issues/2023
- [x] drop support `theme.config` files in favour of passing theme options as `props` in Next.js' `layout` file https://github.com/shuding/nextra/issues/2887
- [x] replace Flexsearch by Pagefind https://github.com/shuding/nextra/issues/2524
- [x] componentize themes by importing Client/Server components (`Banner/Navbar/Footer` etc.) https://github.com/shuding/nextra/issues/332
- [x] remove `useData` hook in favour async server components
- [ ] using both themes https://github.com/shuding/nextra/issues/361
- [ ] i18n blog example https://github.com/shuding/nextra/issues/182
- [ ] https://github.com/shuding/nextra/issues/2024
- [x] `backgroundColor` accept rgb and hex values instead of `11,45,33` format https://github.com/shuding/nextra/issues/2772#issuecomment-1985977827
- [x] https://github.com/shuding/nextra/issues/2872
- [x]  https://github.com/shuding/nextra/issues/2523
- [x] https://github.com/shuding/nextra/issues/1435
- [x] https://github.com/shuding/nextra/issues/959
- [x] https://github.com/shuding/nextra/issues/1611
- [x] https://github.com/shuding/nextra/issues/2946
- [x] https://github.com/shuding/nextra/issues/2516
- [x] https://github.com/shuding/nextra/issues/2300
- [x] https://github.com/shuding/nextra/issues/3121
- [x] https://github.com/shuding/nextra/issues/2238
- [x] https://github.com/shuding/nextra/issues/1634
- [x] https://github.com/shuding/nextra/issues/3264
- [x] https://github.com/shuding/nextra/issues/2016 
- [x] https://github.com/shuding/nextra/issues/1819
- [x] https://github.com/shuding/nextra/issues/1729 
- [x] https://github.com/shuding/nextra/issues/2450 
- [x] https://github.com/shuding/nextra/issues/3405 
- [x] https://github.com/shuding/nextra/issues/3449
- [x] https://github.com/shuding/nextra/issues/3447 
- [x] https://github.com/shuding/nextra/issues/3339
- [x] https://github.com/shuding/nextra/issues/3391
- [x] https://github.com/shuding/nextra/issues/1054
- [x] https://github.com/shuding/nextra/issues/2521
- [ ] https://github.com/shuding/nextra/issues/2438
- [x] https://github.com/shuding/nextra/issues/2448
- [x] https://github.com/shuding/nextra/issues/2088
- [x] https://github.com/shuding/nextra/issues/1299 document how to do it with Pagefind
- [x] https://github.com/shuding/nextra/issues/2755
- [x] https://github.com/shuding/nextra/issues/3090
- [x] https://github.com/shuding/nextra/issues/3486
- [x] https://github.com/shuding/nextra/issues/3468
- [x] https://github.com/shuding/nextra/issues/2425
- [x] https://github.com/shuding/nextra/issues/2276
- [x] https://github.com/shuding/nextra/issues/2116
- [x] https://github.com/shuding/nextra/issues/3673 
- [x] https://github.com/shuding/nextra/issues/1239
- [x] https://github.com/shuding/nextra/issues/2457 document how to do it 
- [x] https://github.com/shuding/nextra/issues/3733 
- [x] https://github.com/shuding/nextra/issues/3736
- [x] https://github.com/shuding/nextra/issues/3730
- [x] https://github.com/shuding/nextra/issues/130 should be fixed with new App Router refactoring
- [x] https://github.com/shuding/nextra/issues/1801 
- [x] https://github.com/shuding/nextra/issues/3802

**Comment by jellli** [comment]
I'm currently adding `twoslash` in v3, would that be a problem?

**Comment by dimaMachina** [comment]
> I'm currently adding `twoslash` in v3, would that be a problem?

no, go with it, ty

**Comment by officialrajdeepsingh** [comment]
Remove the tailwind [prefix `nx-`](https://github.com/shuding/nextra/blob/2f001d897f2109b24600f66fe2009e5f788b980c/packages/nextra-theme-docs/tailwind.config.js#L14C1-L14C1) in nextra component, I can not use nextra component like alert, Cards, etc. in my [custom theme](https://github.com/frontendweb3/section-theme-blog). 


```
@apply nx-h-full nx-float-left nx-pr-4 nx-text-right nx-min-w-[2.6rem] nx-text-gray-500;
```

**Comment by dimaMachina** [comment]
> why drop support for `pages`? why not support both?

because it requires a lot of engineering time, I already maintain this repo alone

**Comment by andriilive** [comment]
Thanks for an awesome job you're doing. 

I'd really really like to see some kind of primitive static data collections API in v14, like **Astro's collections** or **json-server**. 
 https://docs.astro.build/en/tutorials/add-content-collections/
 https://github.com/typicode/json-server

**Comment by andrii-bodnar** [comment]
Probably the [MDX v3](https://mdxjs.com/blog/v3/) is also a good candidate for this release (or maybe even for Nextra v3?).

Thanks for the great project!

**Comment by Zamoca42** [comment]
Hi! I've been looking at issue #2772 regarding `backgroundColor`. I have a few ideas about this and would be interested in contributing if it's not already being worked on.

Would it be helpful if I shared my thoughts or perhaps submitted a pull request with a proposed implementation? I'd be happy to work on this if it's still open for contributions.

Let me know if you'd like me to proceed or if there's any specific guidance I should follow. Thanks!

**Comment by Waylon-Firework** [comment]
when will the v4 be release

**Comment by dimaMachina** [comment]
Nextra v3 was finally released. And Nextra v4 prerelease just out! Currently without docs changes update or migration guide.

Nextra v4 will support a file-based router for your mdx files, 
for anyone who wants to give it a try, feel free to take a look at nextra.site migration https://github.com/shuding/nextra/tree/v4-v2/docs

Nextra v4 will also support rendering your docs from a single catch-all route `app/[[...slug]].jsx`. Currently, as unstable and without hot reloading working, but I will fix it before stable releasing. Feel free to take a look at **blog**/**docs** and **i18n docs** examples that were migrated to it! https://github.com/shuding/nextra/tree/v4-v2/examples

Prerelease v4 last versions:
https://github.com/shuding/nextra/releases/tag/nextra%404.0.0-app-router.4
https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%404.0.0-app-router.4
https://github.com/shuding/nextra/releases/tag/nextra-theme-blog%404.0.0-app-router.4

Feel free to share your feedback and create separated issues for problems you encountered

Have fun!

**Comment by florianamette** [comment]
Is the search feature supposed to work in the latest release (4.0.0-app-router.6) ? 
![image](https://github.com/user-attachments/assets/43e0279b-8c08-46db-89d6-0f5fd03139d3)

**Comment by dimaMachina** [comment]
Yes, the search needs to index built .html files, you must to add `postbuild` script as follows https://github.com/shuding/nextra/blob/c9d0ffc8687644401412b8adc34af220cccddf82/docs/package.json#L9

Also, nextra-theme-blog in v4 has search as well

Check out the last preview https://nextra-v2-6bnfo6seg-shud.vercel.app/ where you can see working search

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/releases/tag/nextra%404.0.0-app-router.13 is just out with Turbopack support

**Comment by lacymorrow** [comment]
Fak yeah dude

**Comment by dimaMachina** [comment]
For everybody waiting for Nextra v4, I am finishing the Blogpost announcement for Nextra v4 RC.0 with all features and migration guide, so stay tuned 😁

**Comment by codewreaker** [comment]
> For everybody waiting for Nextra v4, I am finishing the Blogpost announcement for Nextra v4 RC.0 with all features and migration guide, so stay tuned 😁

Looking forward to it. I am currently using next 15 and searching the whole v4-v2 branch for any information. I will wait for you then

**Comment by olegchursin** [comment]
Nextra v4 is looking 🔥 ! Can't wait for RC.0 and a blogpost @dimaMachina . Thanks for all the work!

**Comment by Thijmen** [comment]
If one would like to start with Nextra v4, which branch should be used in that case? I don't care if it may break or not - just looking for next opportunities to create a docs site :)

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/tree/v4-v2

**Comment by CorruptionTiger** [comment]
If God asked me who the best person in the world is, I would say B2o5T.

**Comment by mcnojo** [comment]
Question: is it possible to host multiple dynamically generated Nextra sites in the same application route?  let say we have a primary application that that will route subdomains apple and orange (or others outside of "www".site.com) to a dynamic catch all route [[...subdomain_docs]].  

Is this a reasonable strategy to present static docs that also use ISR?  

Would we be able to use and apply dynamic theme as well?  Many thanks, I'm new to Nextra :)

**Comment by Firgrep** [comment]
@tomsvetna Put the client component in a separate file and import it, keeping the page a server component. Then add the metadata requirement.

**Comment by SrBrahma** [comment]
@dimaMachina are the v4 docs being hosted anywhere public already?

**Comment by nikischin** [comment]
> @dimaMachina are the v4 docs being hosted anywhere public already?

You should be able to use the latest preview links in #2653

**Comment by dimaMachina** [comment]
Nextra 4 is released https://the-guild.dev/blog/nextra-4

Feel free to submit your PRs to improve Nextra docs

**Comment by steebchen** [comment]
Amazing work @dimaMachina, thanks!

**Comment by ignacionar** [comment]
Thanks @dimaMachina !

**Comment by TheMikeyRoss** [comment]
@dimaMachina you're a legend

**Comment by Genesis3800** [comment]
@dimaMachina my brother I just wanted to say this is amazing work and I love you for all your work on Nextra.

I am going to migrate my company's docs from `Nextra 2` to `Nextra 4`, and I think I have found some bugs in the Nextra 4 docs.
Would you be open to PRs?

**Comment by dimaMachina** [comment]
Thank you very much, docs PRs are highly appreciated 🙏

**Comment by huykon** [comment]
Hi @dimaMachina 
How to use both docs & blog in Nextra 4?

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/4340#issuecomment-2781428352
